name: POC 2 Run Script

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run custom script
        run: |
          chmod +x scripts/sample-script.sh
          ./scripts/sample-script.sh

     
