name: Use Custom Action

on:
  push:
    branches:
      - master  # You can change this to your desired branch
  pull_request:

jobs:
  run-custom-action:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository (this is required to use any action)
      - name: Checkout repository
        uses: actions/checkout@v3  # This will checkout your trial repository

      # Step 2: Use the custom action (GreetAction)
      - name: Greet User
        uses: majid9971/GreetAction/.github/actions/my-action@v1.0.3  # Replace with your repo and release tag
        with:
          name: "Another User"  # Input parameter for the action
